### ISSUE TITLE
Consider Adjusting temperature & Humidity per PurpleAir

### ISSUE THREAD

**Issue by dpwilcock** [tillkruss/homebridge-purpleair#10]
Thanks for developing this.  I've been banging my head against http-advanced-accessory, and your plug-in enabled me to get my purpleair with temp & humidity attached to homekit.  Thank you!

Temperature routinely reads about 4C too high, and humdity a bit on the low side - Purple Air adjusts for this on their map, and at this link include that they basically subtract 8F and add 4% to the humidity due to the heat generated by the device.  
Consider adding these correction factors to your plug-in?

Thanks again for making & sharing this!
-Duncan.

**Comment by tillkruss** [comment]
We're actually already doing that: https://github.com/tillkruss/homebridge-purpleair/blob/2ec1ae47ce7c2b977eda8a6115b2475c68a957ff/src/sensorReading.ts#L100-L122

Do you have a reference sensor that leads you to believe the PA sensors are still a bit off?

**Comment by dpwilcock** [comment]
Wow.  Fantastic! 
I might not have this version yet, I'm on HOOBs.   Will check, but obviously we can close this.  Nicely done!
