### ISSUE TITLE
Adjustable temperature and humidity correction?

### ISSUE THREAD

**Issue by kr-max** [tillkruss/homebridge-purpleair#9]
**Is your feature request related to a problem? Please describe:**
The temperature and humidity from PurpleAir aren’t meant to represent ambient conditions, as they describe here in “A Note on Temperature and Humidity” https://community.purpleair.com/t/purpleair-sensors-functional-overview/150

**Describe the solution you'd like:**
Given that PurpleAir applies both a temperature and humidity correction when this is viewed on the map, it would be helpful to similarly allow a correction to be applied to the temperature and humidity numbers reported to HomeKit through this module.

PurpleAir defaults to adjusting by -8°F and 4% humidity. That seems like a solid default, though it would be nice for the offsets to be adjustable as an advanced option, if users can measure that a different offset is more accurate for their sensor(s).

see attached screenshots for my PurpleAir sensor readings in two rooms compare to the HomePod mini and Eve / Qingping temperature/ humidity sensors next to them in those spaces.
![IMG_4526](https://github.com/tillkruss/homebridge-purpleair/assets/20405250/af26a3d2-c073-4ad7-906c-e9ad7a10dd3e)
![IMG_4527](https://github.com/tillkruss/homebridge-purpleair/assets/20405250/1852db57-17eb-48d9-9cc9-77c08a98dc7f)

Thanks for making this plugin - it’s great to have!

**Comment by tillkruss** [comment]
Thanks for bringing this up. I was wondering why my temperature was higher than the other sensors.

Making this configurable makes sense, too, but consumer temperature sensors seems unreliable, especially HomePods.

**Comment by tillkruss** [comment]
Fixed in ae6f9328b1329acacd2f95cc3f7f2022442d46dd.

**Comment by tillkruss** [comment]
Released in [v1.0.8](https://github.com/tillkruss/homebridge-purpleair/releases/tag/v1.0.8).
